export const GET_ALL_ITEMS = 'GET_ALL_ITEMS';
export const GET_ITEM_IMAGES = 'GET_ITEM_IMAGES';
export const GET_ITEM_FEATURES = 'GET_ITEM_FEATURES';
export const GET_ITEM_COURTESIES = 'GET_ITEM_COURTESIES';
export const GET_WISH_ITEMS = 'GET_WISH_ITEMS';
export const GET_USER_ITEMS = 'GET_USER_ITEMS';
export const ITEM_TRIP_DATE = 'ITEM_TRIP_DATE';

export const SET_USER_ID = 'SET_USER_ID';
export const GET_USER_INFO = 'GET_USER_INFO';
export const SET_USER_VERIFIED = 'SET_USER_VERIFIED';
export const SET_LICENSE_VERIFIED = 'SET_LICENSE_VERIFIED';

export const GET_USER_MESSAGES = 'GET_USER_MESSAGES';

export const GET_PENDING_TRIPS = 'GET_PENDING_TRIPS';
export const GET_PENDING_BOOKINGS = 'GET_PENDING_BOOKINGS';

export const GET_DOCUMENTS = 'GET_DOCUMENTS';

export const RESERVED_TIME = 'RESERVED_TIME';
export const POLICY_DATA = 'POLICY_DATA';